# Generated by Django 3.0.6 on 2020-06-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kosapp', '0002_client_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='docs/pdfs/')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kosapp.Client')),
            ],
        ),
    ]
